Downgrade pydantic version. Resolve a regression causing an `AttributeError: '_SpecialForm' object has no attribute 'replace'` when accessing the /openapi.json endpoint.